### ISSUE TITLE
ImageViewer组件图片遮罩层z-index层级过低

### ISSUE THREAD

**Issue by cloudland0716** [CMHIT-Front/cifc#1]
因ImageViewer遮罩层的层级不够，导致其他弹出遮罩层覆盖在ImageViewer组件上方，引发图片遮罩层可重复显示问题，例如ant-design的Popover组件的z-index为1030，覆盖在ImageViewer组件上方。

**Comment by aaronlam** [comment]
通过传入previewOption属性设置组件zIndex

可以试下传入以下属性：

`previewOption={{
    zIndex: 9999
}}`
